use std::collections::HashMap;

use super::{AllocatedProgram, FnName, SelectorOpt};
use crate::{
    asm_generation::{
        fuel::{
            abstract_instruction_set::AbstractInstructionSet,
            allocated_abstract_instruction_set::AllocatedAbstractInstructionSet,
            compiler_constants,
            data_section::{DataSection, Entry, EntryName},
            globals_section::GlobalsSection,
            register_sequencer::RegisterSequencer,
        },
        ProgramKind,
    },
    asm_lang::{
        allocated_ops::{AllocatedInstruction, AllocatedRegister},
        AllocatedAbstractOp, ConstantRegister, ControlFlowOp, JumpType, Label, Op,
        VirtualImmediate12, VirtualImmediate18, VirtualImmediate24, VirtualOp,
    },
    decl_engine::DeclRefFunction,
    OptLevel,
};
use either::Either;
use sway_error::error::CompileError;
use sway_features::ExperimentalFeatures;
use sway_types::Span;

/// The entry point of an abstract program.
pub(crate) struct AbstractEntry {
    pub(crate) selector: SelectorOpt,
    pub(crate) label: Label,
    pub(crate) ops: AbstractInstructionSet,
    pub(crate) name: FnName,
    pub(crate) test_decl_ref: Option<DeclRefFunction>,
}

/// An [AbstractProgram] represents code generated by the compilation from IR, with virtual registers
/// and abstract control flow.
///
/// Use `AbstractProgram::to_allocated_program()` to perform register allocation.
///
pub(crate) struct AbstractProgram {
    kind: ProgramKind,
    data_section: DataSection,
    globals_section: GlobalsSection,
    before_entries: AbstractInstructionSet,
    entries: Vec<AbstractEntry>,
    non_entries: Vec<AbstractInstructionSet>,
    reg_seqr: RegisterSequencer,
    experimental: ExperimentalFeatures,
}

impl AbstractProgram {
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn new(
        kind: ProgramKind,
        data_section: DataSection,
        globals_section: GlobalsSection,
        before_entries: AbstractInstructionSet,
        entries: Vec<AbstractEntry>,
        non_entries: Vec<AbstractInstructionSet>,
        reg_seqr: RegisterSequencer,
        experimental: ExperimentalFeatures,
    ) -> Self {
        AbstractProgram {
            kind,
            data_section,
            globals_section,
            before_entries,
            entries,
            non_entries,
            reg_seqr,
            experimental,
        }
    }

    /// True if the [AbstractProgram] does not contain any instructions, or entries, or data in the data section.
    pub(crate) fn is_empty(&self) -> bool {
        self.non_entries.is_empty()
            && self.entries.is_empty()
            && self.data_section.iter_all_entries().next().is_none()
    }

    /// Adds prologue, globals allocation, before entries, contract method switch, and allocates virtual register.
    pub(crate) fn into_allocated_program(
        mut self,
        fallback_fn: Option<crate::asm_lang::Label>,
        opt_level: OptLevel,
    ) -> Result<AllocatedProgram, CompileError> {
        let mut prologue = self.build_prologue();
        self.append_globals_allocation(&mut prologue);
        self.append_before_entries(&mut prologue, opt_level)?;

        match (self.experimental.new_encoding, self.kind) {
            (true, ProgramKind::Contract) => {
                self.append_jump_to_entry(&mut prologue);
            }
            (false, ProgramKind::Contract) => {
                self.append_encoding_v0_contract_abi_switch(&mut prologue, fallback_fn);
            }
            _ => {}
        }

        // Keep track of the labels (and names) that represent program entry points.
        let entries: Vec<_> = self
            .entries
            .iter()
            .map(|entry| {
                (
                    entry.selector,
                    entry.label,
                    entry.name.clone(),
                    entry.test_decl_ref.clone(),
                )
            })
            .collect();

        // Gather all functions.
        let all_functions = self
            .entries
            .into_iter()
            .map(|entry| entry.ops)
            .chain(self.non_entries);

        // Optimize and then verify abstract functions.
        let mut optimized_fns = all_functions
            .map(|f| f.optimize(&self.data_section, opt_level))
            .map(AbstractInstructionSet::verify)
            .collect::<Result<Vec<AbstractInstructionSet>, CompileError>>()?;

        Self::optimize_fn_order(&mut optimized_fns);

        // Allocate the registers for each function.
        let allocated_functions = optimized_fns
            .into_iter()
            .map(|abstract_instruction_set| {
                let allocated = abstract_instruction_set.allocate_registers()?;
                Ok(allocated.lower_pusha_popa())
            })
            .collect::<Result<Vec<AllocatedAbstractInstructionSet>, CompileError>>()?;

        // Optimize allocated functions.
        let functions = allocated_functions
            .into_iter()
            .map(|instruction_set| instruction_set.optimize())
            // TODO: Add verification. E.g., verify that:
            //        - function has exactly one CFEI/CFSI pair,
            //        - the stack use for each function is balanced,
            //        - $$locbase is only used if stack has been allocated for it.
            //        - etc.
            // .map(AllocatedAbstractInstructionSet::verify)
            .collect::<Vec<AllocatedAbstractInstructionSet>>();

        Ok(AllocatedProgram {
            kind: self.kind,
            data_section: self.data_section,
            prologue,
            functions,
            entries,
        })
    }

    fn append_before_entries(
        &self,
        prologue: &mut AllocatedAbstractInstructionSet,
        opt_level: OptLevel,
    ) -> Result<(), CompileError> {
        let before_entries = self
            .before_entries
            .clone()
            .optimize(&self.data_section, opt_level);
        let before_entries = before_entries.verify()?;
        let mut before_entries = before_entries.allocate_registers()?;
        prologue.ops.append(&mut before_entries.ops);
        Ok(())
    }

    /// Builds the asm preamble, which includes metadata and a jump past the metadata.
    /// Right now, it looks like this:
    ///
    /// WORD OP
    ///     1    MOV $scratch $pc
    ///     -    JMPF $zero i10
    ///     2    DATA_START (0-32) (in bytes, offset from $is)
    ///     -    DATA_START (32-64)
    ///     3    CONFIGURABLES_OFFSET (0-32)
    ///     -    CONFIGURABLES_OFFSET (32-64)
    ///     4    LW $ds $scratch 1
    ///     -    ADD $ds $ds $scratch
    ///     5    .program_start:
    fn build_prologue(&mut self) -> AllocatedAbstractInstructionSet {
        const _: () = assert!(
            crate::PRELUDE_CONFIGURABLES_OFFSET_IN_BYTES == 16,
            "Inconsistency in the assumption of prelude organisation"
        );
        const _: () = assert!(
            crate::PRELUDE_CONFIGURABLES_SIZE_IN_BYTES == 8,
            "Inconsistency in the assumption of prelude organisation"
        );
        const _: () = assert!(
            crate::PRELUDE_SIZE_IN_BYTES == 32,
            "Inconsistency in the assumption of prelude organisation"
        );
        let label = self.reg_seqr.get_label();
        AllocatedAbstractInstructionSet {
            function: None,
            ops: [
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::MOVE(
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                        AllocatedRegister::Constant(ConstantRegister::ProgramCounter),
                    )),
                    comment: String::new(),
                    owning_span: None,
                },
                // word 1.5
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::Jump {
                        to: label,
                        ty: JumpType::Unconditional,
                    }),
                    comment: String::new(),
                    owning_span: None,
                },
                // word 2 -- full word u64 placeholder
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::DataSectionOffsetPlaceholder),
                    comment: "data section offset".into(),
                    owning_span: None,
                },
                // word 3 -- full word u64 placeholder
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::ConfigurablesOffsetPlaceholder),
                    comment: "configurables offset".into(),
                    owning_span: None,
                },
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::Label(label)),
                    comment: "end of configurables offset".into(),
                    owning_span: None,
                },
                // word 4 -- load the data offset into $ds
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::LW(
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                        VirtualImmediate12::new(1),
                    )),
                    comment: "".into(),
                    owning_span: None,
                },
                // word 4.5 -- add $ds $ds $is
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::ADD(
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                    )),
                    comment: "".into(),
                    owning_span: None,
                },
            ]
            .to_vec(),
        }
    }

    // WHen the new encoding is used, jumps to the `__entry`  function
    fn append_jump_to_entry(&mut self, asm: &mut AllocatedAbstractInstructionSet) {
        let entry = self.entries.iter().find(|x| x.name == "__entry").unwrap();
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Right(ControlFlowOp::Jump {
                to: entry.label,
                ty: JumpType::Unconditional,
            }),
            comment: "jump to ABI function selector".into(),
            owning_span: None,
        });
    }

    /// Builds the contract switch statement based on the first argument to a contract call: the
    /// 'selector'.
    /// See https://fuellabs.github.io/fuel-specs/master/vm#call-frames which
    /// describes the first argument to be at word offset 73.
    fn append_encoding_v0_contract_abi_switch(
        &mut self,
        asm: &mut AllocatedAbstractInstructionSet,
        fallback_fn: Option<crate::asm_lang::Label>,
    ) {
        const SELECTOR_WORD_OFFSET: u64 = 73;
        const INPUT_SELECTOR_REG: AllocatedRegister = AllocatedRegister::Allocated(0);
        const PROG_SELECTOR_REG: AllocatedRegister = AllocatedRegister::Allocated(1);
        const CMP_RESULT_REG: AllocatedRegister = AllocatedRegister::Allocated(2);

        // Build the switch statement for selectors.
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Right(ControlFlowOp::Comment),
            comment: "[function selection]: begin contract function selector switch".into(),
            owning_span: None,
        });

        // Load the selector from the call frame.
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::LW(
                INPUT_SELECTOR_REG,
                AllocatedRegister::Constant(ConstantRegister::FramePointer),
                VirtualImmediate12::new(SELECTOR_WORD_OFFSET),
            )),
            comment: "[function selection]: load input function selector".into(),
            owning_span: None,
        });

        // Add a 'case' for each entry with a selector.
        for entry in &self.entries {
            let selector = match entry.selector {
                Some(sel) => sel,
                // Skip entries that don't have a selector - they're probably tests.
                None => continue,
            };

            // Put the selector in the data section.
            let data_label = self.data_section.insert_data_value(Entry::new_word(
                u32::from_be_bytes(selector) as u64,
                EntryName::NonConfigurable,
                None,
            ));

            // Load the data into a register for comparison.
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::LoadDataId(
                    PROG_SELECTOR_REG,
                    data_label,
                )),
                comment: format!(
                    "[function selection]: load function {} selector for comparison",
                    entry.name
                ),
                owning_span: None,
            });

            // Compare with the input selector.
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::EQ(
                    CMP_RESULT_REG,
                    INPUT_SELECTOR_REG,
                    PROG_SELECTOR_REG,
                )),
                comment: format!(
                    "[function selection]: compare function {} selector with input selector",
                    entry.name
                ),
                owning_span: None,
            });

            // Jump to the function label if the selector was equal.
            asm.ops.push(AllocatedAbstractOp {
                // If the comparison result is _not_ equal to 0, then it was indeed equal.
                opcode: Either::Right(ControlFlowOp::Jump {
                    to: entry.label,
                    ty: JumpType::NotZero(CMP_RESULT_REG),
                }),
                comment: "[function selection]: jump to selected contract function".into(),
                owning_span: None,
            });
        }

        if let Some(fallback_fn) = fallback_fn {
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Right(ControlFlowOp::Jump {
                    to: fallback_fn,
                    ty: JumpType::Call,
                }),
                comment: "[function selection]: call contract fallback function".into(),
                owning_span: None,
            });
        }

        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::MOVI(
                AllocatedRegister::Constant(ConstantRegister::Scratch),
                VirtualImmediate18::new(compiler_constants::MISMATCHED_SELECTOR_REVERT_CODE.into()),
            )),
            comment: "[function selection]: load revert code for mismatched function selector"
                .into(),
            owning_span: None,
        });
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::RVRT(AllocatedRegister::Constant(
                ConstantRegister::Scratch,
            ))),
            comment: "[function selection]: revert if no selectors have matched".into(),
            owning_span: None,
        });
    }

    /// Allocates stack space for globals.
    ///
    /// `cfei` is added to `asm` only if the [Self::globals_section] actually contains globals.
    fn append_globals_allocation(&self, asm: &mut AllocatedAbstractInstructionSet) {
        let len_in_bytes = self.globals_section.len_in_bytes();
        if len_in_bytes > 0 {
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::CFEI(VirtualImmediate24::new(
                    len_in_bytes,
                ))),
                comment: "allocate stack space for globals".into(),
                owning_span: None,
            });
        }
    }

    fn optimize_fn_order(fns: &mut Vec<AbstractInstructionSet>) {
        if fns.len() < 2 {
            return;
        }

        // Real compiled size of a single op, in instruction units (1 instr = 4
        // bytes), mirroring `worst_case_instruction_size` from
        // `allocated_abstract_instruction_set.rs`. Labels/Comments and
        // zero-stack CFEI/CFSI contribute 0; data-section loads and offset
        // placeholders cost 2; a `Call` jump reserves 3 (worst case) and other
        // jumps 2; BLOB is its immediate. PushAll/PopAll are still present
        // here (lowered only later in `lower_pusha_popa`) and expand to at
        // most two push/pop-mask instructions, so we charge 2 rather than
        // panicking like the post-allocation version would.
        let op_size = |op: &Op| -> u64 {
            match &op.opcode {
                Either::Right(ControlFlowOp::Label(_)) => 0,
                Either::Right(ControlFlowOp::Comment) => 0,
                Either::Right(ControlFlowOp::Jump { ty, .. }) => match ty {
                    JumpType::Call => 3,
                    _ => 2,
                },
                Either::Right(ControlFlowOp::JumpToAddr(_)) => 1,
                Either::Right(ControlFlowOp::ReturnFromCall { .. }) => 1,
                Either::Right(ControlFlowOp::DataSectionOffsetPlaceholder) => 2,
                Either::Right(ControlFlowOp::ConfigurablesOffsetPlaceholder) => 2,
                Either::Right(ControlFlowOp::PushAll(_))
                | Either::Right(ControlFlowOp::PopAll(_)) => 2,
                Either::Left(VirtualOp::CFEI(_, ref imm))
                | Either::Left(VirtualOp::CFSI(_, ref imm))
                    if imm.value() == 0 =>
                {
                    0
                }
                Either::Left(VirtualOp::BLOB(ref count)) => count.value() as u64,
                Either::Left(VirtualOp::LoadDataId(_, _) | VirtualOp::AddrDataId(_, _)) => 2,
                Either::Left(_) => 1,
            }
        };

        let n = fns.len();

        // Stable per-function facts. Reordering only permutes whole functions;
        // leading labels, sizes, and call sites never change. A function's
        // first op must be a `Label`; preserve the prior `todo!()` behavior.
        let fn_labels: Vec<usize> = fns
            .iter()
            .map(|f| match f.ops.first() {
                Some(Op {
                    opcode: Either::Right(ControlFlowOp::Label(l)),
                    ..
                }) => l.0,
                _ => todo!(),
            })
            .collect();
        let mut label_to_fn_idx: HashMap<usize, usize> = HashMap::new();
        for (idx, &lab) in fn_labels.iter().enumerate() {
            label_to_fn_idx.insert(lab, idx);
        }
        let fn_sizes: Vec<u64> = fns
            .iter()
            .map(|f| f.ops.iter().map(|o| op_size(o)).sum())
            .collect();
        // Per function: (call-site offset within the function, callee label).
        let call_sites: Vec<Vec<(u64, usize)>> = fns
            .iter()
            .map(|f| {
                let mut sites = Vec::new();
                let mut site_off: u64 = 0;
                for op in f.ops.iter() {
                    if let Either::Right(ControlFlowOp::Jump {
                        to,
                        ty: JumpType::Call,
                    }) = &op.opcode
                    {
                        sites.push((site_off, to.0));
                    }
                    site_off += op_size(op);
                }
                sites
            })
            .collect();

        // Layout state: `best_order[slot] = fn_idx`, `fn_idx_to_slot[fn_idx] = slot`.
        // Kept in sync on every mutation; `fns` is rewritten from `best_order` at
        // the end.
        let mut best_order: Vec<usize> = (0..n).collect();
        let mut fn_idx_to_slot: Vec<usize> = (0..n).collect();
        let sync_slots = |order: &[usize], slot_of: &mut [usize]| {
            for (s, &f) in order.iter().enumerate() {
                slot_of[f] = s;
            }
        };

        // --- Loop detection (gas-oriented weighting) -------------------------
        // The benchmark measures gas, and a call's gas scales with how often it
        // executes. A call inside a loop runs once per iteration, so its
        // execution count grows with loop nesting depth. Loops at the ASM level
        // are backward intra-function jumps (a back-edge to a label earlier in
        // the same function); a call is inside a loop when it sits between the
        // loop header (the back-edge target) and the back-edge site, and its
        // nesting depth is the number of distinct loops enclosing it. This is
        // invariant under reordering (functions move as whole units), so we
        // compute it once on the initial layout and key it by
        // (caller label, call-site offset within the caller).
        let call_loop_depth: HashMap<(usize, u64), usize> = {
            let mut map: HashMap<(usize, u64), usize> = HashMap::new();
            for (fi, f) in fns.iter().enumerate() {
                let caller = fn_labels[fi];
                // Index each label in this function to its op position.
                let mut label_idx: HashMap<usize, usize> = HashMap::new();
                for (i, op) in f.ops.iter().enumerate() {
                    if let Either::Right(ControlFlowOp::Label(l)) = &op.opcode {
                        label_idx.insert(l.0, i);
                    }
                }
                // Back-edges: backward non-call jumps to an earlier label.
                // Group by header, keeping the furthest latch per header so the
                // loop body is the contiguous [header, max_latch] range.
                let mut loops: HashMap<usize, (usize, usize)> = HashMap::new();
                for (j, op) in f.ops.iter().enumerate() {
                    if let Either::Right(ControlFlowOp::Jump { to, ty }) = &op.opcode {
                        match ty {
                            JumpType::Unconditional | JumpType::NotZero(_) => {
                                if let Some(&h) = label_idx.get(&to.0) {
                                    if h < j {
                                        let e = loops.entry(to.0).or_insert((h, j));
                                        if j > e.1 {
                                            e.1 = j;
                                        }
                                    }
                                }
                            }
                            JumpType::Call => {}
                        }
                    }
                }
                if loops.is_empty() {
                    continue;
                }
                let loops: Vec<(usize, usize)> = loops.values().cloned().collect();
                let mut site_off: u64 = 0;
                for (i, op) in f.ops.iter().enumerate() {
                    if let Either::Right(ControlFlowOp::Jump {
                        ty: JumpType::Call, ..
                    }) = &op.opcode
                    {
                        let depth = loops.iter().filter(|(h, l)| *h <= i && i <= *l).count();
                        if depth > 0 {
                            map.insert((caller, site_off), depth);
                        }
                    }
                    site_off += op_size(op);
                }
            }
            map
        };

        // Commit policy toggle. When `PARETO` is true, a relocation is committed
        // only if it is a true Pareto improvement: no individual call gets
        // worse and at least one gets better. This guarantees no per-call
        // regression at the cost of blocking most trades (almost every useful
        // move lengthens some call), so it yields fewer but safer improvements.
        // When false, the aggregate-cost policy with `MIN_GAIN` is used.
        const PARETO: bool = true;
        // Gas weight multiplier per loop nesting level: a call at depth `d` is
        // weighted `LOOP_BOOST^d` times its base instruction cost (depth 0 ->
        // 1x). 2 models each loop roughly doubling execution count; raise it if
        // hot loops have large trip counts.
        const LOOP_BOOST: usize = 4;

        // Per-call weight for the current layout, keyed by
        // (caller label, call-site offset within the caller). The base weight
        // is the call's compiled instruction count, mirroring
        // `compile_call_inner`:
        //   forward near  -> 1  (JAL)
        //   backward near -> 2  (SUBI + JAL)
        //   medium        -> 3  (MOVI +/- + JAL)
        //   far           -> 6  (data section load + JAL; real count is 4, but
        //                       inflated to 6 to penalize far calls harder than
        //                       the medium->near step, so the greedy search
        //                       breaks near-ties toward eliminating far calls)
        // The base weight is then multiplied by `LOOP_BOOST^depth`, so calls in
        // hot loops dominate the cost (gas scales with execution count).
        // Offsets are in instruction units from `op_size` (Label/Comment and
        // zero-stack CFEI/CFSI are 0, not 1), matching the resolver's offset
        // units. Forward near uses the 12-bit JAL immediate directly
        // (`delta <= TWELVE_BITS`); backward near uses a 12-bit SUBI immediate
        // holding `delta * 4` bytes, so its near range is 4x smaller. Counting
        // forward calls too means a move that lengthens a forward call past the
        // near threshold is penalized (1 -> 3), not free. Self-calls travel
        // with their function, so they add a position-independent constant and
        // don't affect which position is chosen.
        let call_weights = |order: &[usize]| -> HashMap<(usize, u64), usize> {
            const FWD_NEAR: usize = 1;
            const BACK_NEAR: usize = 2;
            const MEDIUM: usize = 3;
            const FAR: usize = 6;

            // fn_idx -> offset of the function's start, in instruction units.
            let mut fn_to_off = vec![0u64; n];
            let mut offset: u64 = 0;
            for &fi in order {
                fn_to_off[fi] = offset;
                offset += fn_sizes[fi];
            }

            let mut weights: HashMap<(usize, u64), usize> = HashMap::new();
            for &caller_fi in order {
                let caller = fn_labels[caller_fi];
                let func_start = fn_to_off[caller_fi];
                for &(site_off, to_label) in &call_sites[caller_fi] {
                    if let Some(&target_fi) = label_to_fn_idx.get(&to_label) {
                        let target_off = fn_to_off[target_fi];
                        let call_site = func_start + site_off;
                        let tier = if target_off >= call_site {
                            // Forward (or self): the 12-bit JAL immediate
                            // holds `delta` directly.
                            let delta = target_off - call_site;
                            if delta <= compiler_constants::TWELVE_BITS {
                                FWD_NEAR
                            } else if delta.saturating_sub(1).saturating_mul(4)
                                <= compiler_constants::EIGHTEEN_BITS
                            {
                                MEDIUM
                            } else {
                                FAR
                            }
                        } else {
                            // Backward: the 12-bit SUBI immediate holds
                            // `delta * 4` bytes, so the near range is 4x
                            // smaller.
                            let delta = call_site - target_off;
                            if delta.saturating_mul(4) <= compiler_constants::TWELVE_BITS {
                                BACK_NEAR
                            } else if delta.saturating_add(1).saturating_mul(4)
                                <= compiler_constants::EIGHTEEN_BITS
                            {
                                MEDIUM
                            } else {
                                FAR
                            }
                        };
                        let depth = call_loop_depth
                            .get(&(caller, site_off))
                            .copied()
                            .unwrap_or(0);
                        weights.insert((caller, site_off), tier * LOOP_BOOST.pow(depth as u32));
                    }
                }
            }
            weights
        };

        // Greedy improvement, capped at a small number of iterations. Each
        // iteration finds the function that is called the most *via a backward
        // call* and relocates it to the position (1..len) that minimizes the
        // weighted call cost (forward + backward, see `call_weights`). The
        // function's original position is always among the candidates, so the
        // chosen position is never worse than staying put: the cost monotonically
        // decreases (or stays the same, in which case we stop). Index 0 (the
        // first entry) never moves.
        const MAX_ITERS: usize = 128;
        // When the worst back-jump target can't be improved, fall back to the
        // 2nd-worst, 3rd-worst, ... up to `DEPTH` candidates per iteration,
        // committing the first one that strictly improves the call cost.
        const DEPTH: usize = 10;
        // Minimum cost improvement (in instruction units) required to commit a
        // move. Without this, sub-threshold reshuffles whose gain is within the
        // cost model's rounding (e.g. a call sitting exactly on the near/far
        // boundary flipping by one instruction) get committed and can churn
        // across iterations, accumulating model error. Requiring at least this
        // much real improvement keeps the greedy descent monotone and stable.
        const MIN_GAIN: usize = 30;

        // Index 0 never moves, so the entry is always original fn 0.
        debug_assert_eq!(best_order[0], 0);

        for iter in 0..MAX_ITERS {
            debug_assert_eq!(best_order[0], 0);

            // (fn_idx, back-call count). Indexed by fn_idx while counting; then
            // `select_nth` on `[1..]` so the entry (fn 0) is never a candidate.
            let mut back_call_count: Vec<(usize, usize)> = (0..n).map(|fi| (fi, 0)).collect();
            for (current_slot, &caller_fi) in best_order.iter().enumerate() {
                for &(_, to_label) in &call_sites[caller_fi] {
                    if let Some(&target_fi) = label_to_fn_idx.get(&to_label) {
                        if fn_idx_to_slot[target_fi] < current_slot {
                            back_call_count[target_fi].1 += 1;
                        }
                    }
                }
            }

            let before_weights = call_weights(&best_order);
            let count_before: usize = before_weights.values().sum();
            let mut committed = false;

            // Rank lazily via `select_nth` (worst-first) so we usually only
            // partition once or twice per iteration.
            let candidates = &mut back_call_count[1..];
            let depth = DEPTH.min(candidates.len());
            for k in 0..depth {
                let (_, (target_fi, target_count), _) =
                    candidates.select_nth_unstable_by(k, |a, b| b.1.cmp(&a.1));
                if *target_count == 0 {
                    break; // remaining ranks are also 0
                }

                let target_label = fn_labels[*target_fi];
                let cur = fn_idx_to_slot[*target_fi];
                // `cur >= 1` because the entry (fn_idx 0) was excluded above.

                // Pull the candidate out and try every position 1..=len (never
                // index 0). Keep the position that minimizes the weighted cost.
                best_order.remove(cur);
                sync_slots(&best_order, &mut fn_idx_to_slot);
                let mut best_p = cur;
                let mut best_count = count_before;

                for p in 1..=best_order.len() {
                    best_order.insert(p, *target_fi);
                    sync_slots(&best_order, &mut fn_idx_to_slot);
                    let w = call_weights(&best_order);
                    best_order.remove(p);
                    sync_slots(&best_order, &mut fn_idx_to_slot);
                    let sum: usize = w.values().sum();
                    // Under `PARETO`, only accept a position where no individual
                    // call gets worse and at least one improves (a true Pareto
                    // improvement). Otherwise accept any lower-aggregate
                    // position. `before_weights` was computed on the layout
                    // with this candidate at `cur`, and the candidate is
                    // present at `p` here, so the call sets match by key.
                    let acceptable = if PARETO {
                        w.iter()
                            .all(|(k, &v)| v <= before_weights.get(k).copied().unwrap_or(0))
                            && w.iter()
                                .any(|(k, &v)| v < before_weights.get(k).copied().unwrap_or(0))
                    } else {
                        true
                    };
                    if acceptable && sum < best_count {
                        best_count = sum;
                        best_p = p;
                    }
                }

                // Commit iff an improving position was found. Under `PARETO` a
                // strict aggregate drop is guaranteed whenever a Pareto-safe
                // improvement exists (some weight strictly decreases, none
                // increase); otherwise the `MIN_GAIN` threshold guards against
                // noise-level reshuffles. `cur` is always a candidate position,
                // so we never worsen the layout.
                let commit = if PARETO {
                    best_count < count_before
                } else {
                    best_count + MIN_GAIN <= count_before
                };
                if commit {
                    best_order.insert(best_p, *target_fi);
                    sync_slots(&best_order, &mut fn_idx_to_slot);
                    eprintln!(
                        "optimize_fn_order iter {iter}: call cost {count_before} -> {best_count} (target {target_label} had {target_count} back calls)"
                    );
                    committed = true;
                    break;
                }

                // This candidate couldn't improve; restore and try the next.
                best_order.insert(cur, *target_fi);
                sync_slots(&best_order, &mut fn_idx_to_slot);
            }

            if !committed {
                break; // none of the top-DEPTH candidates could improve; stop.
            }
        }

        // Apply the final layout to `fns`.
        let mut tmp: Vec<_> = std::mem::take(fns).into_iter().map(Some).collect();
        *fns = best_order
            .into_iter()
            .map(|i| tmp[i].take().unwrap())
            .collect();
    }
}

impl std::fmt::Display for AbstractProgram {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, ";; Program kind: {:?}", self.kind)?;

        writeln!(f, ";; --- Before Entries ---")?;
        writeln!(f, "{}\n", self.before_entries)?;

        writeln!(f, ";; --- Entries ---")?;
        for entry in &self.entries {
            writeln!(f, "{}\n", entry.ops)?;
        }
        writeln!(f, ";; --- Functions ---")?;
        for function in &self.non_entries {
            writeln!(f, "{function}\n")?;
        }
        writeln!(f, ";; --- Data ---")?;
        write!(f, "{}", self.data_section)
    }
}
