use std::collections::HashMap;

use super::{AllocatedProgram, FnName, SelectorOpt};
use crate::{
    asm_generation::{
        fuel::{
            abstract_instruction_set::AbstractInstructionSet,
            allocated_abstract_instruction_set::AllocatedAbstractInstructionSet,
            compiler_constants,
            data_section::{DataSection, Entry, EntryName},
            globals_section::GlobalsSection,
            register_sequencer::RegisterSequencer,
        },
        ProgramKind,
    },
    asm_lang::{
        allocated_ops::{AllocatedInstruction, AllocatedRegister},
        AllocatedAbstractOp, ConstantRegister, ControlFlowOp, JumpType, Label, VirtualImmediate12,
        VirtualImmediate18, VirtualImmediate24,
    },
    decl_engine::DeclRefFunction,
    OptLevel,
};
use either::Either;
use sway_error::error::CompileError;
use sway_features::ExperimentalFeatures;

/// The entry point of an abstract program.
pub(crate) struct AbstractEntry {
    pub(crate) selector: SelectorOpt,
    pub(crate) label: Label,
    pub(crate) ops: AbstractInstructionSet,
    pub(crate) name: FnName,
    pub(crate) test_decl_ref: Option<DeclRefFunction>,
}

/// An [AbstractProgram] represents code generated by the compilation from IR, with virtual registers
/// and abstract control flow.
///
/// Use `AbstractProgram::to_allocated_program()` to perform register allocation.
///
pub(crate) struct AbstractProgram {
    kind: ProgramKind,
    data_section: DataSection,
    globals_section: GlobalsSection,
    before_entries: AbstractInstructionSet,
    entries: Vec<AbstractEntry>,
    non_entries: Vec<AbstractInstructionSet>,
    reg_seqr: RegisterSequencer,
    experimental: ExperimentalFeatures,
}

impl AbstractProgram {
    #[allow(clippy::too_many_arguments)]
    pub(crate) fn new(
        kind: ProgramKind,
        data_section: DataSection,
        globals_section: GlobalsSection,
        before_entries: AbstractInstructionSet,
        entries: Vec<AbstractEntry>,
        non_entries: Vec<AbstractInstructionSet>,
        reg_seqr: RegisterSequencer,
        experimental: ExperimentalFeatures,
    ) -> Self {
        AbstractProgram {
            kind,
            data_section,
            globals_section,
            before_entries,
            entries,
            non_entries,
            reg_seqr,
            experimental,
        }
    }

    /// True if the [AbstractProgram] does not contain any instructions, or entries, or data in the data section.
    pub(crate) fn is_empty(&self) -> bool {
        self.non_entries.is_empty()
            && self.entries.is_empty()
            && self.data_section.iter_all_entries().next().is_none()
    }

    /// Adds prologue, globals allocation, before entries, contract method switch, and allocates virtual register.
    pub(crate) fn into_allocated_program(
        mut self,
        fallback_fn: Option<crate::asm_lang::Label>,
        opt_level: OptLevel,
    ) -> Result<AllocatedProgram, CompileError> {
        let mut prologue = self.build_prologue();
        self.append_globals_allocation(&mut prologue);
        self.append_before_entries(&mut prologue, opt_level)?;

        match (self.experimental.new_encoding, self.kind) {
            (true, ProgramKind::Contract) => {
                self.append_jump_to_entry(&mut prologue);
            }
            (false, ProgramKind::Contract) => {
                self.append_encoding_v0_contract_abi_switch(&mut prologue, fallback_fn);
            }
            _ => {}
        }

        // Keep track of the labels (and names) that represent program entry points.
        let entries: Vec<_> = self
            .entries
            .iter()
            .map(|entry| {
                (
                    entry.selector,
                    entry.label,
                    entry.name.clone(),
                    entry.test_decl_ref.clone(),
                )
            })
            .collect();

        // Gather all functions.
        let all_functions = self
            .entries
            .into_iter()
            .map(|entry| entry.ops)
            .chain(self.non_entries);

        // Optimize and then verify abstract functions.
        let mut optimized_fns = all_functions
            .map(|f| f.optimize(&self.data_section, opt_level))
            .map(AbstractInstructionSet::verify)
            .collect::<Result<Vec<AbstractInstructionSet>, CompileError>>()?;

        Self::optimize_fn_order(&mut optimized_fns);

        // Allocate the registers for each function.
        let allocated_functions = optimized_fns
            .into_iter()
            .map(|abstract_instruction_set| {
                let allocated = abstract_instruction_set.allocate_registers()?;
                Ok(allocated.lower_pusha_popa())
            })
            .collect::<Result<Vec<AllocatedAbstractInstructionSet>, CompileError>>()?;

        // Optimize allocated functions.
        let functions = allocated_functions
            .into_iter()
            .map(|instruction_set| instruction_set.optimize())
            // TODO: Add verification. E.g., verify that:
            //        - function has exactly one CFEI/CFSI pair,
            //        - the stack use for each function is balanced,
            //        - $$locbase is only used if stack has been allocated for it.
            //        - etc.
            // .map(AllocatedAbstractInstructionSet::verify)
            .collect::<Vec<AllocatedAbstractInstructionSet>>();

        Ok(AllocatedProgram {
            kind: self.kind,
            data_section: self.data_section,
            prologue,
            functions,
            entries,
        })
    }

    fn append_before_entries(
        &self,
        prologue: &mut AllocatedAbstractInstructionSet,
        opt_level: OptLevel,
    ) -> Result<(), CompileError> {
        let before_entries = self
            .before_entries
            .clone()
            .optimize(&self.data_section, opt_level);
        let before_entries = before_entries.verify()?;
        let mut before_entries = before_entries.allocate_registers()?;
        prologue.ops.append(&mut before_entries.ops);
        Ok(())
    }

    /// Builds the asm preamble, which includes metadata and a jump past the metadata.
    /// Right now, it looks like this:
    ///
    /// WORD OP
    ///     1    MOV $scratch $pc
    ///     -    JMPF $zero i10
    ///     2    DATA_START (0-32) (in bytes, offset from $is)
    ///     -    DATA_START (32-64)
    ///     3    CONFIGURABLES_OFFSET (0-32)
    ///     -    CONFIGURABLES_OFFSET (32-64)
    ///     4    LW $ds $scratch 1
    ///     -    ADD $ds $ds $scratch
    ///     5    .program_start:
    fn build_prologue(&mut self) -> AllocatedAbstractInstructionSet {
        const _: () = assert!(
            crate::PRELUDE_CONFIGURABLES_OFFSET_IN_BYTES == 16,
            "Inconsistency in the assumption of prelude organisation"
        );
        const _: () = assert!(
            crate::PRELUDE_CONFIGURABLES_SIZE_IN_BYTES == 8,
            "Inconsistency in the assumption of prelude organisation"
        );
        const _: () = assert!(
            crate::PRELUDE_SIZE_IN_BYTES == 32,
            "Inconsistency in the assumption of prelude organisation"
        );
        let label = self.reg_seqr.get_label();
        AllocatedAbstractInstructionSet {
            function: None,
            ops: [
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::MOVE(
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                        AllocatedRegister::Constant(ConstantRegister::ProgramCounter),
                    )),
                    comment: String::new(),
                    owning_span: None,
                },
                // word 1.5
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::Jump {
                        to: label,
                        ty: JumpType::Unconditional,
                    }),
                    comment: String::new(),
                    owning_span: None,
                },
                // word 2 -- full word u64 placeholder
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::DataSectionOffsetPlaceholder),
                    comment: "data section offset".into(),
                    owning_span: None,
                },
                // word 3 -- full word u64 placeholder
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::ConfigurablesOffsetPlaceholder),
                    comment: "configurables offset".into(),
                    owning_span: None,
                },
                AllocatedAbstractOp {
                    opcode: Either::Right(ControlFlowOp::Label(label)),
                    comment: "end of configurables offset".into(),
                    owning_span: None,
                },
                // word 4 -- load the data offset into $ds
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::LW(
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                        VirtualImmediate12::new(1),
                    )),
                    comment: "".into(),
                    owning_span: None,
                },
                // word 4.5 -- add $ds $ds $is
                AllocatedAbstractOp {
                    opcode: Either::Left(AllocatedInstruction::ADD(
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::DataSectionStart),
                        AllocatedRegister::Constant(ConstantRegister::Scratch),
                    )),
                    comment: "".into(),
                    owning_span: None,
                },
            ]
            .to_vec(),
        }
    }

    // WHen the new encoding is used, jumps to the `__entry`  function
    fn append_jump_to_entry(&mut self, asm: &mut AllocatedAbstractInstructionSet) {
        let entry = self.entries.iter().find(|x| x.name == "__entry").unwrap();
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Right(ControlFlowOp::Jump {
                to: entry.label,
                ty: JumpType::Unconditional,
            }),
            comment: "jump to ABI function selector".into(),
            owning_span: None,
        });
    }

    /// Builds the contract switch statement based on the first argument to a contract call: the
    /// 'selector'.
    /// See https://fuellabs.github.io/fuel-specs/master/vm#call-frames which
    /// describes the first argument to be at word offset 73.
    fn append_encoding_v0_contract_abi_switch(
        &mut self,
        asm: &mut AllocatedAbstractInstructionSet,
        fallback_fn: Option<crate::asm_lang::Label>,
    ) {
        const SELECTOR_WORD_OFFSET: u64 = 73;
        const INPUT_SELECTOR_REG: AllocatedRegister = AllocatedRegister::Allocated(0);
        const PROG_SELECTOR_REG: AllocatedRegister = AllocatedRegister::Allocated(1);
        const CMP_RESULT_REG: AllocatedRegister = AllocatedRegister::Allocated(2);

        // Build the switch statement for selectors.
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Right(ControlFlowOp::Comment),
            comment: "[function selection]: begin contract function selector switch".into(),
            owning_span: None,
        });

        // Load the selector from the call frame.
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::LW(
                INPUT_SELECTOR_REG,
                AllocatedRegister::Constant(ConstantRegister::FramePointer),
                VirtualImmediate12::new(SELECTOR_WORD_OFFSET),
            )),
            comment: "[function selection]: load input function selector".into(),
            owning_span: None,
        });

        // Add a 'case' for each entry with a selector.
        for entry in &self.entries {
            let selector = match entry.selector {
                Some(sel) => sel,
                // Skip entries that don't have a selector - they're probably tests.
                None => continue,
            };

            // Put the selector in the data section.
            let data_label = self.data_section.insert_data_value(Entry::new_word(
                u32::from_be_bytes(selector) as u64,
                EntryName::NonConfigurable,
                None,
            ));

            // Load the data into a register for comparison.
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::LoadDataId(
                    PROG_SELECTOR_REG,
                    data_label,
                )),
                comment: format!(
                    "[function selection]: load function {} selector for comparison",
                    entry.name
                ),
                owning_span: None,
            });

            // Compare with the input selector.
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::EQ(
                    CMP_RESULT_REG,
                    INPUT_SELECTOR_REG,
                    PROG_SELECTOR_REG,
                )),
                comment: format!(
                    "[function selection]: compare function {} selector with input selector",
                    entry.name
                ),
                owning_span: None,
            });

            // Jump to the function label if the selector was equal.
            asm.ops.push(AllocatedAbstractOp {
                // If the comparison result is _not_ equal to 0, then it was indeed equal.
                opcode: Either::Right(ControlFlowOp::Jump {
                    to: entry.label,
                    ty: JumpType::NotZero(CMP_RESULT_REG),
                }),
                comment: "[function selection]: jump to selected contract function".into(),
                owning_span: None,
            });
        }

        if let Some(fallback_fn) = fallback_fn {
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Right(ControlFlowOp::Jump {
                    to: fallback_fn,
                    ty: JumpType::Call,
                }),
                comment: "[function selection]: call contract fallback function".into(),
                owning_span: None,
            });
        }

        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::MOVI(
                AllocatedRegister::Constant(ConstantRegister::Scratch),
                VirtualImmediate18::new(compiler_constants::MISMATCHED_SELECTOR_REVERT_CODE.into()),
            )),
            comment: "[function selection]: load revert code for mismatched function selector"
                .into(),
            owning_span: None,
        });
        asm.ops.push(AllocatedAbstractOp {
            opcode: Either::Left(AllocatedInstruction::RVRT(AllocatedRegister::Constant(
                ConstantRegister::Scratch,
            ))),
            comment: "[function selection]: revert if no selectors have matched".into(),
            owning_span: None,
        });
    }

    /// Allocates stack space for globals.
    ///
    /// `cfei` is added to `asm` only if the [Self::globals_section] actually contains globals.
    fn append_globals_allocation(&self, asm: &mut AllocatedAbstractInstructionSet) {
        let len_in_bytes = self.globals_section.len_in_bytes();
        if len_in_bytes > 0 {
            asm.ops.push(AllocatedAbstractOp {
                opcode: Either::Left(AllocatedInstruction::CFEI(VirtualImmediate24::new(
                    len_in_bytes,
                ))),
                comment: "allocate stack space for globals".into(),
                owning_span: None,
            });
        }
    }

    fn optimize_fn_order(fns: &mut Vec<AbstractInstructionSet>) {
        const MAX_ITERS: usize = 128;
        const DEPTH: usize = 10;

        if fns.len() < 2 {
            return;
        }

        let mut layout = FnLayout::new(fns);

        'improve: for _ in 0..MAX_ITERS {
            // Index 0 never moves, so the entry is always original fn 0.
            debug_assert_eq!(layout.order[0], 0);

            let mut found_improvement = false;

            let before_weights = layout.call_weights(None);
            let before_weights_sum = before_weights.values().sum::<usize>();

            let mut back_call_count = layout.back_call_count();
            let candidates = &mut back_call_count[1..];
            let depth = DEPTH.min(candidates.len());

            'candidates: for k in 0..depth {
                let (_, (candidate_fn, candidate_count), _) =
                    candidates.select_nth_unstable_by(k, |a, b| b.1.cmp(&a.1));
                if *candidate_count == 0 {
                    break 'candidates;
                }

                let candidate_fn = *candidate_fn;
                let candidate_slot = layout.slot_of(candidate_fn);

                // Try candidate in every possible position
                let mut best_slot = candidate_slot;
                let mut best_weights_sum = before_weights_sum;
                for slot_being_tried in 1..layout.len() {
                    let candidate_weights =
                        layout.call_weights(Some((candidate_slot, slot_being_tried)));
                    let candidate_sum = candidate_weights.values().sum();

                    // Only accept a position where no individual call gets worse
                    // and at least one improves
                    let no_call_worse = candidate_weights.iter().all(|(call_key, &new_weight)| {
                        let old_weight = before_weights.get(call_key).copied().unwrap_or(0);
                        new_weight <= old_weight
                    });
                    let some_call_better =
                        candidate_weights.iter().any(|(call_key, &new_weight)| {
                            let old_weight = before_weights.get(call_key).copied().unwrap_or(0);
                            new_weight < old_weight
                        });
                    let acceptable = no_call_worse && some_call_better;
                    if acceptable && candidate_sum < best_weights_sum {
                        best_weights_sum = candidate_sum;
                        best_slot = slot_being_tried;
                    }
                }

                // If an improvement was found, accept it
                if best_weights_sum < before_weights_sum {
                    layout.relocate(candidate_slot, best_slot);

                    // Uncoment this to log improvements
                    // eprintln!(
                    //     "optimize_fn_order iter {iter}: call cost {before_weights_sum} -> {best_count} (target fn {target_fi} had {target_count} back calls)"
                    // );

                    found_improvement = true;
                    break 'candidates;
                }
            }

            if !found_improvement {
                break 'improve;
            }
        }

        layout.apply();
    }
}

impl std::fmt::Display for AbstractProgram {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(f, ";; Program kind: {:?}", self.kind)?;

        writeln!(f, ";; --- Before Entries ---")?;
        writeln!(f, "{}\n", self.before_entries)?;

        writeln!(f, ";; --- Entries ---")?;
        for entry in &self.entries {
            writeln!(f, "{}\n", entry.ops)?;
        }
        writeln!(f, ";; --- Functions ---")?;
        for function in &self.non_entries {
            writeln!(f, "{function}\n")?;
        }
        writeln!(f, ";; --- Data ---")?;
        write!(f, "{}", self.data_section)
    }
}

struct CallSite {
    caller: usize,
    offset: u64,
    callee: usize,
}

struct FnLayout<'a> {
    fns: &'a mut Vec<AbstractInstructionSet>,
    fn_sizes: Vec<u64>,
    call_sites: Vec<CallSite>,
    /// Keyed by (caller fn_idx, call-site offset within the caller).
    call_loop_depth: HashMap<(usize, u64), usize>,
    order: Vec<usize>,
}

impl<'a> FnLayout<'a> {
    /// Entry label of a function.
    fn label_of(f: &AbstractInstructionSet) -> Label {
        f.ops
            .iter()
            .find_map(|op| match &op.opcode {
                Either::Right(ControlFlowOp::Label(l)) => Some(*l),
                _ => None,
            })
            .unwrap_or_else(|| {
                panic!(
                    "function {:?} has no Label in its ops (len={})",
                    f.function,
                    f.ops.len()
                )
            })
    }

    fn new(fns: &'a mut Vec<AbstractInstructionSet>) -> Self {
        let n = fns.len();

        let fn_labels = fns.iter().map(Self::label_of).collect::<Vec<_>>();
        let fn_sizes = fns
            .iter()
            .map(|f| f.ops.iter().map(|o| o.op_size()).sum())
            .collect();
        let label_to_fn_idx: HashMap<Label, usize> = fn_labels
            .iter()
            .enumerate()
            .map(|(idx, &lab)| (lab, idx))
            .collect();

        let mut call_sites = Vec::with_capacity(n);
        for (caller, f) in fns.iter().enumerate() {
            let mut site_off: u64 = 0;
            for op in f.ops.iter() {
                if let Either::Right(ControlFlowOp::Jump {
                    to,
                    ty: JumpType::Call,
                }) = &op.opcode
                {
                    if let Some(&callee) = label_to_fn_idx.get(to) {
                        call_sites.push(CallSite {
                            caller,
                            offset: site_off,
                            callee,
                        });
                    }
                }
                site_off += op.op_size();
            }
        }

        // use to boost call inside of loops
        let mut call_loop_depth = HashMap::new();
        for (idx, f) in fns.iter().enumerate() {
            // Index each label in this function to its op position.
            let mut label_idx = HashMap::new();
            for (i, op) in f.ops.iter().enumerate() {
                if let Either::Right(ControlFlowOp::Label(l)) = &op.opcode {
                    label_idx.insert(l.0, i);
                }
            }

            // Find loops
            // Header: The single entry point of a loop that dominates all other nodes within it.
            // Latch: A node inside the loop that has a jump to the header.
            let mut loops = HashMap::new();
            for (latch, op) in f.ops.iter().enumerate() {
                if let Either::Right(ControlFlowOp::Jump { to, ty }) = &op.opcode {
                    match ty {
                        JumpType::Unconditional | JumpType::NotZero(_) => {
                            if let Some(&header) = label_idx.get(&to.0) {
                                if header < latch {
                                    let entry = loops.entry(to.0).or_insert((header, latch));
                                    if latch > entry.1 {
                                        entry.1 = latch;
                                    }
                                }
                            }
                        }
                        JumpType::Call => {}
                    }
                }
            }

            if loops.is_empty() {
                continue;
            }

            let loops = loops.values().cloned().collect::<Vec<_>>();

            // Calculate each call site loop depth
            // The more deep a call is, more boost it will gain
            let mut site_offset: u64 = 0;
            for (i, op) in f.ops.iter().enumerate() {
                if let Either::Right(ControlFlowOp::Jump {
                    ty: JumpType::Call, ..
                }) = &op.opcode
                {
                    let depth = loops
                        .iter()
                        .filter(|(header, latch)| *header <= i && i <= *latch)
                        .count();
                    if depth > 0 {
                        call_loop_depth.insert((idx, site_offset), depth);
                    }
                }
                site_offset += op.op_size();
            }
        }

        Self {
            fns,
            fn_sizes,
            call_sites,
            call_loop_depth,
            order: (0..n).collect(),
        }
    }

    fn len(&self) -> usize {
        self.order.len()
    }

    fn slot_of(&self, fn_idx: usize) -> usize {
        self.order
            .iter()
            .position(|&f| f == fn_idx)
            .expect("fn_idx present in order")
    }

    /// `(fn_idx, back-call count)` for every function in the current layout.
    fn back_call_count(&self) -> Vec<(usize, usize)> {
        let n = self.fn_sizes.len();
        let mut slot_of = vec![0usize; n];

        for (slot, &fi) in self.order.iter().enumerate() {
            slot_of[fi] = slot;
        }

        let mut counts = (0..n).map(|fi| (fi, 0)).collect::<Vec<_>>();
        for site in &self.call_sites {
            if slot_of[site.callee] < slot_of[site.caller] {
                counts[site.callee].1 += 1;
            }
        }

        counts
    }

    /// `virtual_move` means (original position, new position).
    /// Returns per-call weights keyed by `(caller fn_idx, call-site offset)`.
    fn call_weights(&self, virtual_move: Option<(usize, usize)>) -> HashMap<(usize, u64), usize> {
        const LOOP_BOOST: usize = 4;

        // fn_idx -> offset of the function's start, in instruction units.
        let n = self.fn_sizes.len();
        let mut fn_to_off = vec![0u64; n];
        let mut offset: u64 = 0;
        match virtual_move {
            None => {
                for &fi in &self.order {
                    fn_to_off[fi] = offset;
                    offset += self.fn_sizes[fi];
                }
            }
            Some((from, to)) => {
                let fi = self.order[from];
                for slot in 0..n {
                    let f = if slot == to {
                        fi
                    } else {
                        // Compacted index in the post-remove sequence.
                        let c = if slot < to { slot } else { slot - 1 };
                        self.order[if c < from { c } else { c + 1 }]
                    };
                    fn_to_off[f] = offset;
                    offset += self.fn_sizes[f];
                }
            }
        }

        let mut weights = HashMap::new();
        for site in &self.call_sites {
            let func_start = fn_to_off[site.caller];
            let target_off = fn_to_off[site.callee];
            let call_site = func_start + site.offset;

            let jmp_factor = jmp_weight_factor(target_off, call_site);
            let depth = self
                .call_loop_depth
                .get(&(site.caller, site.offset))
                .copied()
                .unwrap_or(0);

            weights.insert(
                (site.caller, site.offset),
                jmp_factor * LOOP_BOOST.pow(depth as u32),
            );
        }
        weights
    }

    fn relocate(&mut self, from: usize, to: usize) {
        let fi = self.order.remove(from);
        self.order.insert(to, fi);
    }

    fn apply(self) {
        let mut tmp: Vec<_> = std::mem::take(self.fns).into_iter().map(Some).collect();
        *self.fns = self
            .order
            .into_iter()
            .map(|i| tmp[i].take().unwrap())
            .collect();
    }
}

fn jmp_weight_factor(target_off: u64, call_site: u64) -> usize {
    const FWD_NEAR: usize = 1;
    const BACK_NEAR: usize = 2;
    const MEDIUM: usize = 3;
    const FAR: usize = 6;

    if target_off >= call_site {
        let delta = target_off - call_site;
        if delta <= compiler_constants::TWELVE_BITS {
            FWD_NEAR
        } else if delta.saturating_sub(1).saturating_mul(4) <= compiler_constants::EIGHTEEN_BITS {
            MEDIUM
        } else {
            FAR
        }
    } else {
        let delta = call_site - target_off;
        if delta.saturating_mul(4) <= compiler_constants::TWELVE_BITS {
            BACK_NEAR
        } else if delta.saturating_add(1).saturating_mul(4) <= compiler_constants::EIGHTEEN_BITS {
            MEDIUM
        } else {
            FAR
        }
    }
}
