library huge_enum;

pub enum Huge {
    a1: (),
    b1: (),
    c1: (),
    d1: (),
    e1: (),
    f1: (),
    g1: (),
    h1: (),
    a2: (),
    b2: (),
    c2: (),
    d2: (),
    e2: (),
    f2: (),
    g2: (),
    h2: (),
    a3: (),
    b3: (),
    c3: (),
    d3: (),
    e3: (),
    f3: (),
    g3: (),
    h3: (),
    a4: (),
    b4: (),
    c4: (),
    d4: (),
    e4: (),
    f4: (),
    g4: (),
    h4: (),
    a5: (),
    b5: (),
    c5: (),
    d5: (),
    e5: (),
    f5: (),
    g5: (),
    h5: (),
    a6: (),
    b6: (),
    c6: (),
    d6: (),
    e6: (),
    f6: (),
    g6: (),
    h6: (),
    a7: (),
    b7: (),
    c7: (),
    d7: (),
    e7: (),
    f7: (),
    g7: (),
    h7: (),
    a8: (),
    b8: (),
    c8: (),
    d8: (),
    e8: (),
    f8: (),
    g8: (),
    h8: (),
}

impl Huge {
    pub fn to_u64(self) -> u64 {
        match self {
            Huge::a1 => 0,
            Huge::b1 => 1,
            Huge::c1 => 2,
            Huge::d1 => 3,
            Huge::e1 => 4,
            Huge::f1 => 5,
            Huge::g1 => 6,
            Huge::h1 => 7,
            Huge::a2 => 8,
            Huge::b2 => 9,
            Huge::c2 => 10,
            Huge::d2 => 11,
            Huge::e2 => 12,
            Huge::f2 => 13,
            Huge::g2 => 14,
            Huge::h2 => 15,
            Huge::a3 => 16,
            Huge::b3 => 17,
            Huge::c3 => 18,
            Huge::d3 => 19,
            Huge::e3 => 20,
            Huge::f3 => 21,
            Huge::g3 => 22,
            Huge::h3 => 23,
            Huge::a4 => 24,
            Huge::b4 => 25,
            Huge::c4 => 26,
            Huge::d4 => 27,
            Huge::e4 => 28,
            Huge::f4 => 29,
            Huge::g4 => 30,
            Huge::h4 => 31,
            Huge::a5 => 32,
            Huge::b5 => 33,
            Huge::c5 => 34,
            Huge::d5 => 35,
            Huge::e5 => 36,
            Huge::f5 => 37,
            Huge::g5 => 38,
            Huge::h5 => 39,
            Huge::a6 => 40,
            Huge::b6 => 41,
            Huge::c6 => 42,
            Huge::d6 => 43,
            Huge::e6 => 44,
            Huge::f6 => 45,
            Huge::g6 => 46,
            Huge::h6 => 47,
            Huge::a7 => 48,
            Huge::b7 => 49,
            Huge::c7 => 50,
            Huge::d7 => 51,
            Huge::e7 => 52,
            Huge::f7 => 53,
            Huge::g7 => 54,
            Huge::h7 => 55,
            Huge::a8 => 56,
            Huge::b8 => 57,
            Huge::c8 => 58,
            Huge::d8 => 59,
            Huge::e8 => 60,
            Huge::f8 => 61,
            Huge::g8 => 62,
            Huge::h8 => 63,
        }
    }

    pub fn from_u64(index: u64) -> Huge {
        match index {
            0 => Huge::a1,
            1 => Huge::b1,
            2 => Huge::c1,
            3 => Huge::d1,
            4 => Huge::e1,
            5 => Huge::f1,
            6 => Huge::g1,
            7 => Huge::h1,
            8 => Huge::a2,
            9 => Huge::b2,
            10 => Huge::c2,
            11 => Huge::d2,
            12 => Huge::e2,
            13 => Huge::f2,
            14 => Huge::g2,
            15 => Huge::h2,
            16 => Huge::a3,
            17 => Huge::b3,
            18 => Huge::c3,
            19 => Huge::d3,
            20 => Huge::e3,
            21 => Huge::f3,
            22 => Huge::g3,
            23 => Huge::h3,
            24 => Huge::a4,
            25 => Huge::b4,
            26 => Huge::c4,
            27 => Huge::d4,
            28 => Huge::e4,
            29 => Huge::f4,
            30 => Huge::g4,
            31 => Huge::h4,
            32 => Huge::a5,
            33 => Huge::b5,
            34 => Huge::c5,
            35 => Huge::d5,
            36 => Huge::e5,
            37 => Huge::f5,
            38 => Huge::g5,
            39 => Huge::h5,
            40 => Huge::a6,
            41 => Huge::b6,
            42 => Huge::c6,
            43 => Huge::d6,
            44 => Huge::e6,
            45 => Huge::f6,
            46 => Huge::g6,
            47 => Huge::h6,
            48 => Huge::a7,
            49 => Huge::b7,
            50 => Huge::c7,
            51 => Huge::d7,
            52 => Huge::e7,
            53 => Huge::f7,
            54 => Huge::g7,
            55 => Huge::h7,
            56 => Huge::a8,
            57 => Huge::b8,
            58 => Huge::c8,
            59 => Huge::d8,
            60 => Huge::e8,
            61 => Huge::f8,
            62 => Huge::g8,
            63 => Huge::h8,
            _ => Huge::e8,
        }
    }
}

impl core::ops::Eq for Huge {
    fn eq(self, other: Self) -> bool {
        match (self, other) {
            (Huge::a1, Huge::a1) => true,
            (Huge::a2, Huge::a2) => true,
            (Huge::a3, Huge::a3) => true,
            (Huge::a4, Huge::a4) => true,
            (Huge::a5, Huge::a5) => true,
            (Huge::a6, Huge::a6) => true,
            (Huge::a7, Huge::a7) => true,
            (Huge::a8, Huge::a8) => true,
            //
            (Huge::b1, Huge::b1) => true,
            (Huge::b2, Huge::b2) => true,
            (Huge::b3, Huge::b3) => true,
            (Huge::b4, Huge::b4) => true,
            (Huge::b5, Huge::b5) => true,
            (Huge::b6, Huge::b6) => true,
            (Huge::b7, Huge::b7) => true,
            (Huge::b8, Huge::b8) => true,
            //
            (Huge::c1, Huge::c1) => true,
            (Huge::c2, Huge::c2) => true,
            (Huge::c3, Huge::c3) => true,
            (Huge::c4, Huge::c4) => true,
            (Huge::c5, Huge::c5) => true,
            (Huge::c6, Huge::c6) => true,
            (Huge::c7, Huge::c7) => true,
            (Huge::c8, Huge::c8) => true,
            //
            (Huge::d1, Huge::d1) => true,
            (Huge::d2, Huge::d2) => true,
            (Huge::d3, Huge::d3) => true,
            (Huge::d4, Huge::d4) => true,
            (Huge::d5, Huge::d5) => true,
            (Huge::d6, Huge::d6) => true,
            (Huge::d7, Huge::d7) => true,
            (Huge::d8, Huge::d8) => true,
            //
            (Huge::e1, Huge::e1) => true,
            (Huge::e2, Huge::e2) => true,
            (Huge::e3, Huge::e3) => true,
            (Huge::e4, Huge::e4) => true,
            (Huge::e5, Huge::e5) => true,
            (Huge::e6, Huge::e6) => true,
            (Huge::e7, Huge::e7) => true,
            (Huge::e8, Huge::e8) => true,
            //
            (Huge::f1, Huge::f1) => true,
            (Huge::f2, Huge::f2) => true,
            (Huge::f3, Huge::f3) => true,
            (Huge::f4, Huge::f4) => true,
            (Huge::f5, Huge::f5) => true,
            (Huge::f6, Huge::f6) => true,
            (Huge::f7, Huge::f7) => true,
            (Huge::f8, Huge::f8) => true,
            //
            (Huge::g1, Huge::g1) => true,
            (Huge::g2, Huge::g2) => true,
            (Huge::g3, Huge::g3) => true,
            (Huge::g4, Huge::g4) => true,
            (Huge::g5, Huge::g5) => true,
            (Huge::g6, Huge::g6) => true,
            (Huge::g7, Huge::g7) => true,
            (Huge::g8, Huge::g8) => true,
            //
            (Huge::h1, Huge::h1) => true,
            (Huge::h2, Huge::h2) => true,
            (Huge::h3, Huge::h3) => true,
            (Huge::h4, Huge::h4) => true,
            (Huge::h5, Huge::h5) => true,
            (Huge::h6, Huge::h6) => true,
            (Huge::h7, Huge::h7) => true,
            (Huge::h8, Huge::h8) => true,
            _ => false,
        }
    }
}
