testgen!(
    test_str_vec,
    "test_artifacts/storage_vec/svec_str/out/debug/svec_str-abi.json",
    "str",
    ::fuels::types::SizedAsciiString::<4>,
    ::fuels::types::SizedAsciiString::<4>::new("yeet".to_string()).unwrap(),
    ::fuels::types::SizedAsciiString::<4>::new("meow".to_string()).unwrap(),
    ::fuels::types::SizedAsciiString::<4>::new("kekw".to_string()).unwrap(),
    ::fuels::types::SizedAsciiString::<4>::new("gmgn".to_string()).unwrap(),
    ::fuels::types::SizedAsciiString::<4>::new("sway".to_string()).unwrap()
);
