testgen!(
    test_str_vec,
    "test_artifacts/storage_vec/svec_str/out/debug/svec_str-abi.json",
    "str",
    ::fuels::types::AsciiString,
    ::fuels::types::AsciiString::new("yeet".to_string()).unwrap(),
    ::fuels::types::AsciiString::new("meow".to_string()).unwrap(),
    ::fuels::types::AsciiString::new("kekw".to_string()).unwrap(),
    ::fuels::types::AsciiString::new("gmgn".to_string()).unwrap(),
    ::fuels::types::AsciiString::new("sway".to_string()).unwrap()
);
