testgen!(
    test_str_vec,
    "test_artifacts/storage_vec/svec_str/out/debug/svec_str-abi.json",
    "str",
    String,
    "yeet".to_string(),
    "meow".to_string(),
    "kekw".to_string(),
    "gmgn".to_string(),
    "sway".to_string()
);
