echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/stdlib/raw_slice/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/prelude_access/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/self_impl_reassignment/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/retd_struct/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/out_of_order_decl/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_fn_args_u32/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/while_loops/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_generic_traits/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ret_string_in_struct/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_trait/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/unary_not_basic/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_desugaring/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/typeinfo_custom_callpath2/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/size_of/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/typeinfo_custom_callpath/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/unary_not_basic_2/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/typeinfo_custom_callpath_with_import/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/mutable_arrays_nested/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/retd_small_array/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_fn_args_struct_assign/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ops/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/numeric_constants/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/trait_nested/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_fn_args_struct/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/name_resolution_inside_intrinsics/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_functions/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/primitive_type_argument/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/mutable_arrays_struct/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_generic_tuple/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_fn_args_bool/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/use_absolute_path/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_arrays/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/nested_while_and_if/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/redundant_return/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/op_precedence/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/trait_import_with_star/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/struct_destructuring/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/reassignment_operators/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/name_resolution_after_monomorphization/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/str_slice/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/use_full_path_names/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/retd_zero_len_array/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/mutable_arrays/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_single_element/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_structs/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_arrays_inline/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_impls/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_access/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/struct_instantiation/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/unit_type_variants/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/struct_field_reassignment/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_traits/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/supertraits/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_field_reassignment/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/supertraits_with_trait_methods/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/mutable_arrays_swap/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/predicate_while_dep/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/new_allocator_test/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/type_alias/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/trait_method_qualified/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/predicate_while/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/mutable_arrays_enum/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_types/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_in_struct/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/same_const_name/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/nested_structs/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/u256/u256_abi/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_control_flow_expressions/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_parts_of_aggregates/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/dereferencing_control_flow_expressions/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/dereferencing_operator_star/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/trait_method_ascription_disambiguate/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/prelude_access2/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/type_unification_of_references/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ref_mutable_fn_args_call/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_local_vars_and_values/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/dereferencing_operator_dot_on_tuples/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/dereferencing_operator_index/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/ret_small_string/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/retd_b256/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/zero_field_types/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_expressions/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/references_and_generics/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/references_in_aggregates/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/dereferencing_operator_dot_on_structs/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_references/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/mutability_of_references/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/where_clause_enums/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/passing_and_returning_references_to_and_from_functions/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/references_in_asm_blocks/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/impl_reference_types/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/references_and_type_aliases/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/main_args/main_args_predicate/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/raw_ptr/raw_ptr_ret/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/references/referencing_function_parameters/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/raw_identifiers/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/raw_ptr/vec_ret/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/non_literal_const_decl/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/tuple_indexing/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/struct_field_access/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/trait_method_generic_qualified/test.toml
echo -e "\nexpected_result_new_encoding = { action = \"return_data\", value = \"0000000000000001\" }\n" >> should_pass/language/nested_struct_destructuring/test.toml